language: java
after_success:
 - mvn org.jacoco:jacoco-maven-plugin:report
 - mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=${project.reporting.outputDirectory}/jacoco/jacoco.xml -DprojectToken=${CODACY_PROJECT_TOKEN} -DapiToken=${CODACY_API_TOKEN}
jdk:
 - openjdk11